# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Update README CI

on:
  push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Use Node.js 14
      uses: actions/setup-node@v1   
      with:
        node-version: '14'
    - run: |
          npm install
          node ./updateREADME.js
          git config --global user.name 'solidw'
          git config --global user.email 'solidw@naver.com'
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/$GITHUB_REPOSITORY
          git add .
          git commit -am "docs: Update README.md"
          git push

